spring:
  datasource:
    # Added ?options=-c%20timezone=UTC to fix the "Asia/Calcutta" error
    url: jdbc:postgresql://localhost:5432/guardrail_db?options=-c%20timezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Moved jackson out of datasource to the correct spring level
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379